### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showConversation' of undefined

### ISSUE THREAD

**Issue by Zigzag968** [callahanrts/slack-chat#15]
I just typed the "L" key on some JS code, then i got this error

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'showConversation' of undefined

```
At /Users/guibert/.atom/packages/slack-chat/lib/views/conversation-view.coffee:58

TypeError: Cannot read property 'showConversation' of undefined
  at ConversationView.module.exports.ConversationView.openConversation (/Users/guibert/.atom/packages/slack-chat/lib/views/conversation-view.coffee:58:19)
  at ConversationView.openConversation (/Users/guibert/.atom/packages/slack-chat/lib/views/conversation-view.coffee:2:1)
  at Commands.module.exports.Commands.openConversation (/Users/guibert/.atom/packages/slack-chat/lib/commands.coffee:14:34)
  at Commands.openConversation (/Users/guibert/.atom/packages/slack-chat/lib/commands.coffee:2:1)
  at atom-workspace.<anonymous> (/Users/guibert/.atom/packages/slack-chat/lib/slack-chat.coffee:34:102)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  2x -5:53.6.0 pane:split-left (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -5:17 slack-chat:toggle (atom-text-editor.editor.is-focused)
     -1:14.7.0 slack-chat:open-conversation (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.4.0 slack-chat:open-conversation (atom-text-editor.editor.is-focused)
     -0:09.4.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -0:06.8.0 slack-chat:open-conversation (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "shiny-ui",
      "monokai-light"
    ],
    "disabledPackages": [
      "tree-view-breadcrumb"
    ]
  },
  "slack-chat": {
    "token": "xoxp-5183510438-6317145587-6318915362-6e1125"
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
file-icons, v1.5.7
monokai-light, v0.3.7
project-manager, v1.15.10
shiny-ui, v0.33.0
slack-chat, v3.0.3

# Dev
No dev packages
```

**Comment by callahanrts** [comment]
Fixed as of v3.0.4
I switched the command bindings from modal to static. See [the wiki](https://github.com/callahanrts/slack-chat/wiki/Slack-Chat-Keybindings) for the new bindings.
