### ISSUE TITLE
Uncaught TypeError: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by dwillitzer** [callahanrts/slack-chat#17]
[Enter steps to reproduce below:]
1. Opened up channel commenting works. Go to use Back Arrow this error crashs Slack-Chat.  

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.4
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.1.7
### Stack Trace

Uncaught TypeError: Cannot read property 'channel' of undefined

```
At /Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:111

TypeError: Cannot read property 'channel' of undefined
  at StateController.module.exports.StateController.stateChat (/Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:111:31)
  at StateController.stateChat (/Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:2:1)
  at StateController.module.exports.StateController.setState (/Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:108:24)
  at StateController.setState (/Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:2:1)
  at StateController.module.exports.StateController.previousState (/Users/DJ/.atom/packages/slack-chat/lib/state-controller.coffee:98:6)
  at ChatView.module.exports.ChatView.closeChat (/Users/DJ/.atom/packages/slack-chat/lib/views/chat-view.coffee:29:22)
  at HTMLSpanElement.<anonymous> (/Users/DJ/.atom/packages/slack-chat/lib/views/chat-view.coffee:2:1)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -0:36.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:36.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:33.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:31.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.8.0 slack-chat:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "silent-sync",
      "remote-edit",
      "run-command",
      "atom-terminal",
      "atom-terminal-panel"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "slack-chat": {
    "preloadChat": true,
    "api_key": "4207139224.6476382018",
    "api_secret": "52b464df3e028edc8a65a22ea2a7abc7",
    "api_token": "xoxp-4207139224-4207139232-6476444400-cecee1"
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.3
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-sass, v0.1.0
browser-refresh, v0.9.0
color-picker, v2.0.4
command-logger, v0.23.0
css-comb, v2.1.1
editor-stats, v0.17.0
emmet, v2.3.10
file-icons, v1.5.7
git-log, v0.4.1
git-tab-status, v1.9.2
language-htaccess, v0.1.1
linter-bootlint, v0.0.6
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-phpmd, v0.0.11
meteor-api, v2.19.0
minimap, v4.10.0
minimap-git-diff, v4.1.3
pretty-json, v0.3.3
project-colorize, v0.2.0
project-manager, v1.15.10
project-palette-finder, v2.4.17
react, v0.12.0
remote-atom, v1.2.6
remote-sync, v3.1.2
search, v0.5.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
slack-chat, v3.1.7
ssh-config, v0.10.1
svg-preview, v0.6.0
terminal, v0.28.0
tree-view-git-status, v0.1.1
webbox-color, v0.5.7
wordpress, v0.2.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by callahanrts** [comment]
As of 3.1.8 the back button reverts do default state rather than previous state. This error shouldn't occur anymore.
