### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uploadSelection' of undefined

### ISSUE THREAD

**Issue by JeanMertz** [callahanrts/slack-chat#24]
With a chat channel open, but no active text window and/or selected text.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.2
### Stack Trace

Uncaught TypeError: Cannot read property 'uploadSelection' of undefined

```
At /Users/Jean/.atom/packages/slack-chat/lib/commands.coffee:11

TypeError: Cannot read property 'uploadSelection' of undefined
  at atom-workspace.<anonymous> (/Users/Jean/.atom/packages/slack-chat/lib/commands.coffee:11:103)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
     -1:22.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:22 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:22 slack-chat:move-up (atom-pane.pane.active)
     -0:46.6.0 command-palette:toggle (atom-pane.pane.active)
  2x -0:44.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.1.0 slack-chat:move-down (atom-pane.pane.active)
     -0:19.6.0 command-palette:toggle (atom-pane.pane.active)
  3x -0:17.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:16.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.5.0 slack-chat:upload-selection (atom-pane.pane.active)
     -0:04.4.0 command-palette:toggle (atom-pane.pane.active)
     -0:02.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  3x -0:01.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 slack-chat:upload-selection (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ctags",
      "goto"
    ]
  },
  "slack-chat": {
    "api_key": "xxx",
    "api_secret": "yyy",
    "notifications": false,
    "api_token": "zzz"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-ctags, v0.2.0
autocomplete-paths, v1.0.2
docblockr, v0.7.2
highlight-selected, v0.10.1
language-docker, v1.1.3
language-gherkin, v1.0.2
linter, v1.1.0
linter-rubocop, v0.2.7
minimap, v4.10.0
slack-chat, v3.2.2

# Dev
No dev packages
```

**Comment by callahanrts** [comment]
seems to have been fixed along with the other errors.
