### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reverse' of undefined

### ISSUE THREAD

**Issue by alexkahn** [callahanrts/slack-chat#29]
[Enter steps to reproduce below:]
1. Toggled slack panel
2. Attempted to open a DM

**NOTE** OAuth was fine on set-up.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.8
### Stack Trace

Uncaught TypeError: Cannot read property 'reverse' of undefined

```
At /Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:47

TypeError: Cannot read property 'reverse' of undefined
  at /Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:47:74
  at /Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:147:18
  at done (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:355:7)
  at PassThrough.<anonymous> (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:523:9)
  at emitNone (events.js:72:20)
  at PassThrough.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -0:10.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:09.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.4.0 slack-chat:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/Alex/Projects"
  },
  "slack-chat": {
    "api_key": "****",
    "api_secret": "****",
    "api_token": "****"
  }
}
```
### Installed Packages

``` coffee
# User
figlet, v0.4.0
linter, v1.1.0
minimap, v4.10.1
slack-chat, v3.2.8

# Dev
No dev packages
```

**Comment by benlipp** [comment]
Same error here.
1. In the main Slack App, use the /remind command.
2. When Slackbot sends you the reminder, this error will be thrown

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.8

### Stack Trace

Uncaught TypeError: Cannot read property 'reverse' of undefined

```
At /Users/phatlipp/.atom/packages/slack-chat/lib/views/chat-view.coffee:47

TypeError: Cannot read property 'reverse' of undefined
  at /Users/phatlipp/.atom/packages/slack-chat/lib/views/chat-view.coffee:47:74
  at /Users/phatlipp/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:147:18
  at done (/Users/phatlipp/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:355:7)
  at PassThrough.<anonymous> (/Users/phatlipp/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:523:9)
  at emitNone (events.js:72:20)
  at PassThrough.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -8:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:12.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -8:12.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -8:11.1.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -8:10.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:09.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 24x -7:52.2.0 core:undo (atom-text-editor.editor.is-focused)
     -7:44.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:13.2.0 git-plus:menu (textarea.form-control.native-key-bindings)
     -4:12 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:10.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:10.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:55 git-plus:log (atom-text-editor.editor.is-focused)
  5x -3:03.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:59.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:29.5.0 core:select-all (textarea.form-control.native-key-bindings)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "atom-typescript",
      "language-jade"
    ]
  },
  "slack-chat": {
    "api_secret": "[REDACTED]",
    "api_key": "[REDACTED]",
    "api_token": "[REDACTED]"
  }
}
```

### Installed Packages

``` coffee
# User
.bin, vundefined
angularjs, v0.3.0
atom-beautify, v0.28.7
atom-pair, v1.1.6
color-picker, v2.0.7
docblockr, v0.7.2
git-plus, v5.2.2
linter, v1.1.0
merge-conflicts, v1.3.2
minimap, v4.10.1
remote-atom, v1.2.6
seti-ui, v0.7.1
slack-chat, v3.2.8

# Dev
No dev packages
```

**Comment by JohannesMattsson** [comment]
## Made a quick fix to solve the error that occurs when trying to get the history

I made the @type to 'im' if false(not set)
Chat-view.coffee, row 22-33

<pre>
  initialize: (@stateController, @chat) ->
    @width(400)
    @type = 'im'
    @type =
      switch
        when @chat.is_channel? then 'channels'
        when @chat.is_im? then 'im'
        when @chat.is_group? then 'groups'
    if !@type
      @type = 'im'
    @getChatLog()
    @eventHandlers()
</pre>

**Comment by alexkahn** [comment]
Still getting the error:

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.8

### Stack Trace

Uncaught TypeError: Cannot read property 'reverse' of undefined

```
At /Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:47

TypeError: Cannot read property 'reverse' of undefined
  at /Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:47:74
  at /Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:147:18
  at done (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:355:7)
  at PassThrough.<anonymous> (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:523:9)
  at emitNone (events.js:72:20)
  at PassThrough.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:33.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:13 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:10.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 slack-chat:toggle (atom-text-editor.editor)
     -0:06.1.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/Alex/Projects",
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-javac"
    ]
  },
  "slack-chat": {
    "api_key": "*******************",
    "api_secret": "**************************",
    "api_token": "***********************"
  }
}
```

### Installed Packages

``` coffee
# User
figlet, v0.4.0
language-docker, v1.1.3
linter, v1.2.3
minimap, v4.11.2
slack-chat, v3.2.8

# Dev
No dev packages
```

**Comment by diramos1** [comment]
same error here

**Comment by dakotayounger** [comment]
Also getting the same error even with the edit

**Comment by Marviel** [comment]
Same error here

**Comment by gbinflames** [comment]
JohannesMattsson's fix worked for me!

**Comment by joshcoody** [comment]
Same error here

**Comment by krkxone** [comment]
same here

**Comment by vip3rousmango** [comment]
I am experiencing this error as well.

**Comment by RenDvila** [comment]
Here too.
