### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by JeanMertz** [callahanrts/slack-chat#30]
opening a new file using `atom ~/.newfile`, resulted in the following error:

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.8
### Stack Trace

Uncaught TypeError: Cannot read property 'body' of undefined

```
At /Users/Jean/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:112

TypeError: Cannot read property 'body' of undefined
  at /Users/Jean/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:112:28
  at done (/Users/Jean/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:355:7)
  at ClientRequest.had_error (/Users/Jean/.atom/packages/slack-chat/node_modules/sc-client/node_modules/needle/lib/needle.js:362:5)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:166:7)
  at TLSSocket.socketCloseListener (_http_client.js:230:9)
  at emitOne (events.js:82:20)
  at TLSSocket.emit (events.js:166:7)
  at TCP.close (net.js:464:12)

```
### Commands

```
     -0:08.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:03.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:03.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ctags",
      "goto",
      "ask-stack",
      "wrap-guide"
    ],
    "audioBeep": false,
    "projectHome": "/Users/Jean/code"
  },
  "slack-chat": {
    "api_key": "xxx",
    "api_secret": "yyy",
    "notifications": false,
    "api_token": "zzz"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-ctags, v0.2.0
autocomplete-paths, v1.0.2
docblockr, v0.7.2
file-icons, v1.5.8
git-projects, v1.14.1
highlight-selected, v0.10.1
language-docker, v1.1.3
language-gherkin, v1.0.2
linter, v1.1.0
linter-rubocop, v0.2.7
minimap, v4.10.0
minimap-highlight-selected, v4.3.0
multi-wrap-guide, v0.20.0
slack-chat, v3.2.8
synced-sidebar, v0.4.0

# Dev
No dev packages
```

**Comment by bhaskardabhi-oviyum** [comment]
Its still occurring any solution?

**Comment by paulando** [comment]
Toggling "Load conversations on startup" in Slack Chat settings and restarting atom helps me to avoid this error.
