### ISSUE TITLE
Uncaught TypeError: Cannot read property 'receiveMessage' of undefined

### ISSUE THREAD

**Issue by alexkahn** [callahanrts/slack-chat#31]
**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.8
### Stack Trace

Uncaught TypeError: Cannot read property 'receiveMessage' of undefined

```
At /Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:60

TypeError: Cannot read property 'receiveMessage' of undefined
  at ChatView.module.exports.ChatView.receiveMessage (/Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:60:17)
  at ChatView.receiveMessage (/Users/Alex/.atom/packages/slack-chat/lib/views/chat-view.coffee:2:1)
  at StateController.module.exports.StateController.updateChat (/Users/Alex/.atom/packages/slack-chat/lib/state-controller.coffee:155:37)
  at StateController.updateChat (/Users/Alex/.atom/packages/slack-chat/lib/state-controller.coffee:2:1)
  at StateController.module.exports.StateController.message (/Users/Alex/.atom/packages/slack-chat/lib/state-controller.coffee:72:6)
  at StateController.message (/Users/Alex/.atom/packages/slack-chat/lib/state-controller.coffee:2:1)
  at /Users/Alex/.atom/packages/slack-chat/lib/state-controller.coffee:56:7
  at WebSocket.<anonymous> (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:133:27)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:169:7)
  at Receiver.ontext (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/WebSocket.js:797:10)
  at /Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:473:18
  at Receiver.applyExtensions (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:360:5)
  at /Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:462:14
  at Receiver.flush (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:336:3)
  at Receiver.opcodes.1.finish (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:478:12)
  at Receiver.expectHandler (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:453:31)
  at Receiver.add (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/Receiver.js:91:24)
  at TLSSocket.firstHandler (/Users/Alex/.atom/packages/slack-chat/node_modules/sc-client/node_modules/ws/lib/WebSocket.js:774:22)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:109:10)
  at TLSWrap.onread (net.js:517:20)

```
### Commands

```
     -2:28.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:08.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:07.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:07.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:07.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:05.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:02.6.0 slack-chat:toggle (atom-text-editor.editor)
     -2:01.5.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/Alex/Projects",
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "linter-javac"
    ]
  },
  "slack-chat": {
    "api_key": "******************************",
    "api_secret": "*****************************",
    "api_token": "********************************"
  }
}
```
### Installed Packages

``` coffee
# User
figlet, v0.4.0
language-docker, v1.1.3
linter, v1.2.3
minimap, v4.11.2
slack-chat, v3.2.8

# Dev
No dev packages
```

**Comment by joshcoody** [comment]
Same error here

**Comment by Marviel** [comment]
Same error here

**Comment by vip3rousmango** [comment]
Same error here as well. 

TypeError: Cannot read property 'receiveMessage' of undefined
    at ChatView.module.exports.ChatView.receiveMessage (/Users/tpmpro3/.atom/packages/slack-chat/lib/views/chat-view.coffee:125:23)
    at ChatView.receiveMessage (/Users/tpmpro3/.atom/packages/slack-chat/lib/views/chat-view.coffee:3:61)
    at StateController.module.exports.StateController.updateChat (/Users/tpmpro3/.atom/packages/slack-chat/lib/state-controller.coffee:176:50)
    at StateController.updateChat (/Users/tpmpro3/.atom/packages/slack-chat/lib/state-controller.coffee:3:61)
    at StateController.module.exports.StateController.message (/Users/tpmpro3/.atom/packages/slack-chat/lib/state-controller.coffee:93:12)
    at StateController.message (/Users/tpmpro3/.atom/packages/slack-chat/lib/state-controller.coffee:3:61)
    at /Users/tpmpro3/.atom/packages/slack-chat/lib/state-controller.coffee:76:78
    at WebSocket.<anonymous> (/Users/tpmpro3/.atom/packages/slack-chat/node_modules/sc-client/lib/app.js:133:27)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:169:7)

**Comment by weedgrease** [comment]
Still getting this error as well.

**Comment by eric-hansen** [comment]
Getting same error on Atom 1.3.1; is there any resolution in sight for this?

**Comment by RacerDelux** [comment]
Is this repo being managed still?

**Comment by eric-hansen** [comment]
I'm guessing no since this has been open for almost a year and seems like no one has touched the issue since 12/05/2015.
