### ISSUE TITLE
callSite.getFileName is not a function

### ISSUE THREAD

**Issue by jlarrigan** [callahanrts/slack-chat#37]
1. Fresh package install
2. Restart Atom
3. Co-workers on 1.1.0 have 0 issues. 

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.10
### Stack Trace

Failed to activate the slack-chat package

```
At callSite.getFileName is not a function

TypeError: callSite.getFileName is not a function
    at callSiteLocation (/Users/jlarrigan/.atom/packages/slack-chat/node_modules/sc-client/node_modules/express/node_modules/depd/index.js:260:23)
    at depd (/Users/jlarrigan/.atom/packages/slack-chat/node_modules/sc-client/node_modules/express/node_modules/depd/index.js:120:14)
    at Object.<anonymous> (/Users/jlarrigan/.atom/packages/slack-chat/node_modules/sc-client/node_modules/express/lib/router/index.js:21:32)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jlarrigan/.atom/packages/slack-chat/node_modules/sc-client/node_modules/express/lib/application.js:17:14)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "atom-dark-ui",
      "slime"
    ]
  },
  "slack-chat": {
    "api_key": "******",
    "api_secret": "*********",
    "preloadChat": true
  }
}
```
### Installed Packages

``` coffee
# User
jsonlint, v1.1.2
slack-chat, v3.2.10
slime, v1.4.0
terminal-plus, v0.14.2

# Dev
No dev packages
```

**Comment by callahanrts** [comment]
There was an issue including the express package after the latest atom release. Since this isn't the first time I've run into issues with it, I moved the server for oauth redirects to a sinatra app. The updated readme documents the new oauth flow.

**Comment by sunkuangdong** [comment]
I also have a problem, because my node is 10.x. I upgrade my node to 14 then all right
