### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of undefined

### ISSUE THREAD

**Issue by anguspiv** [callahanrts/slack-chat#38]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.2.10
### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of undefined

```
At /Users/angusperkerson/.atom/packages/slack-chat/lib/state-controller.coffee:204

TypeError: Cannot read property 'isVisible' of undefined
    at StateController.module.exports.StateController.toggle (/Users/angusperkerson/.atom/packages/slack-chat/lib/state-controller.coffee:204:26)
    at StateController.toggle (/Users/angusperkerson/.atom/packages/slack-chat/lib/state-controller.coffee:3:61)
    at Object.module.exports.SlackChat.toggle (/Users/angusperkerson/.atom/packages/slack-chat/lib/slack-chat.coffee:69:35)
    at atom-workspace.<anonymous> (/Users/angusperkerson/.atom/packages/slack-chat/lib/slack-chat.coffee:57:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:12 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 slack-chat:toggle (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tail",
      "linter-htmlhint",
      "branch-status",
      "lcov-info",
      "linter-php",
      "language-babel"
    ],
    "destroyEmptyPanes": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/angusperkerson/Workspace"
  },
  "slack-chat": {
    ...
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.1
atom-beautify, v0.28.19
atom-color-highlight, v3.0.9
atom-handlebars, v1.2.0
atom-jasmine, v0.8.1
atom-material-syntax, v0.2.6
atom-material-ui, v1.0.1
auto-update-packages, v1.0.0
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
build, v0.49.2
build-gulp, v0.4.0
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.2.2
file-icons, v1.6.13
fonts, v1.0.0
github-utils, v0.8.0
imdone-atom, v1.3.2
language-apache, v1.3.0
language-c, v0.50.1
language-gitignore, v0.2.0
language-html, v0.43.0
language-ini, v1.14.0
language-java, v0.17.0
language-javascript, v0.103.0
language-json, v0.17.1
language-mustache, v0.13.0
language-opencl, v0.1.1
language-php, v0.34.0
language-puppet, v0.15.0
language-ruby, v0.65.0
language-sass, v0.44.1
language-shellscript, v0.21.0
language-sql, v0.19.0
language-svg, v0.9.0
language-todo, v0.27.0
language-xml, v0.34.1
language-yaml, v0.24.0
linter, v1.11.3
linter-csslint, v1.1.0
linter-handlebars, v2.2.0
linter-js-yaml, v1.2.4
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-jsonlint, v1.1.0
linter-ruby, v1.2.0
linter-scss-lint, v2.4.0
linter-tidy, v1.0.1
linter-xmllint, v1.1.0
minimap, v4.16.2
minimap-color-highlight, v4.1.4
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
php-debug, v0.1.4
php-introspector, v1.0.0
pigments, v0.19.1
project-manager, v2.6.5
slack-chat, v3.2.10
svg-preview, v0.6.1
test-status, v0.35.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8
tree-view-git-status, v0.2.2
view-tail-large-files, v0.2.1
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by humor4fun** [comment]
probably best not to include your slack api token in postings on the web

**Comment by anguspiv** [comment]
Dang it, that was produced by Atom.io's automatic reporting, didn't even think of that. Thanks for pointing it out to me.
