### ISSUE TITLE
Uncaught Error: Unable to determine the domain name

### ISSUE THREAD

**Issue by jfreeman** [callahanrts/slack-chat#40]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v3.4.2
### Stack Trace

Uncaught Error: Unable to determine the domain name

```
At _http_client.js:26

Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:26:13)
    at Object.exports.request (http.js:31:10)
    at Object.exports.get (http.js:35:21)
    at Object.exports.getHTML (/Users/jfreeman/.atom/packages/slack-chat/node_modules/open-graph/index.js:34:26)
    at IncomingMessage.<anonymous> (/Users/jfreeman/.atom/packages/slack-chat/node_modules/open-graph/index.js:46:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "vim-mode"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "slack-chat": {
    "api_key": "6704890869.35925638967",
    "api_secret": "b4513abaadae653dbcbd0ff0be7ebf7a",
    "api_token": "xoxp-6704890869-6704709316-35919078900-ae972bceb0",
    "preloadChat": true
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
drupal, v1.8.0
famous-atom, v3.2.6
javascript-snippets, v1.2.1
language-r, v0.4.0
meteor-api, v2.20.0
php-twig, v4.0.0
phpunit, v1.2.0
slack-chat, v3.4.2
wordcount, v2.6.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by humor4fun** [comment]
Probably best not to include your slack api token in postings on the web

**Comment by brettneese** [comment]
Also experiencing this.
