### ISSUE TITLE
Uncaught TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by Dashon-Hawkins** [callahanrts/slack-chat#46]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package 3.4.2

### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At url.js:87

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at WebSocket.initAsClient (/packages/slack-chat/node_modules/ws/lib/WebSocket.js:550:23)
    at /packages/slack-chat/node_modules/ws/lib/WebSocket.js:74:18)
    at SlackClient.module.exports.SlackClient.webSocket (/packages/slack-chat/lib/slack-client.coffee:40:19)
    at SlackClient.webSocket (/packages/slack-chat/lib/slack-client.coffee:2:1)
    at /packages/slack-chat/lib/slack-client.coffee:37:8
    at done (/packages/slack-chat/node_modules/needle/lib/needle.js:355:7)
    at /packages/slack-chat/node_modules/needle/lib/needle.js:523:9)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -5:31 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.tinted-tab-bar.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-colorblind-wombat-dark-syntax.theme-atom-material-ui)
     -0:40.8.0 settings-view:open (a.)
```

### Non-Core Packages

```
ajax-request 0.1.0 
angularjs 0.4.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-json-editor 0.4.1 
atom-material-ui 1.3.9 
atom-math 0.0.9 
atom-runner 2.7.1 
atom-ternjs 0.18.2 
atomic-chrome 0.3.0 
atomify 0.2.0 
autoclose-html 0.23.0 
autocomplete-json 5.3.0 
busy 0.7.0 
class-complete 6.2.2 
colorblind-wombat-dark-syntax 0.6.0 
colorful-json 1.1.0 
convert-html-to-js 1.0.1 
css-specificity 0.2.2 
element-finder 0.1.1 
es6-javascript 1.0.0 
eval-javascript 1.2.0 
file-icon-supplement 0.8.3 
file-icons 2.0.17 
Function_Index 0.3.2 
git-plus 7.3.3 
html-head-snippets 0.2.0 
html-id-class-snippets 1.4.1 
html-nested-comments 3.3.1 
html-tab 1.0.2 
html-template-generator 0.3.0 
html-to-css 0.2.2 
html-to-elm 0.2.0 
html-to-javascript 0.2.0 
hyperclick 0.0.40 
incompatible 0.0.0 
increment-selection 0.3.0 
indent-guide-improved 1.4.12 
intentions 1.1.2 
java-classpath-registry 0.4.0 
javascript-object-snippets 0.3.0 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
jQuery 1.2.5 
jquery-snippets 11.0.0 
js-func-viewer 1.1.4 
js-patterns-atom-snippets 0.2.1 
json-colorer 1.0.0 
json-path-finder 0.1.9 
jsonpp 0.1.1 
language-fish-shell 1.0.5 
language-javascript-jsx 0.3.7 
language-javascript-semantic 0.2.1 
linter 1.11.23 
linter-json-lint 0.1.1 
linter-spell 0.12.6 
linter-spell-html 0.6.1 
linter-spell-javascript 0.7.1 
pigments 0.39.0 
pretty-json 1.6.1 
Quick-JavaScript 2.2.0 
regex-filter-and-generator 1.4.2 
regex-railroad-diagram 0.16.0 
regex-tester 0.2.0 
save-session 0.15.7 
selector-to-tag 0.4.2 
slack-chat 3.4.2 
sub-atom 1.0.0 
termination 0.5.0 
text-to-string-for-javascript-converter 0.0.7 
turbo-javascript 1.4.0 
```

**Comment by vmharrel** [comment]
I got the same error:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package 3.4.2


### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At url.js:87

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at WebSocket.initAsClient (/packages/slack-chat/node_modules/ws/lib/WebSocket.js:550:23)
    at /packages/slack-chat/node_modules/ws/lib/WebSocket.js:74:18)
    at SlackClient.module.exports.SlackClient.webSocket (/packages/slack-chat/lib/slack-client.coffee:40:19)
    at SlackClient.webSocket (/packages/slack-chat/lib/slack-client.coffee:2:1)
    at /packages/slack-chat/lib/slack-client.coffee:37:8
    at done (/packages/slack-chat/node_modules/needle/lib/needle.js:355:7)
    at /packages/slack-chat/node_modules/needle/lib/needle.js:523:9)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-ember-cli 0.1.3 
atom-foundation-6 0.2.0 
atom-zurb-foundation 2.0.0 
emberjs-atom 0.10.0 
es6-javascript 1.0.0 
node-debugger 1.10.1 
nodejs-snippets 2.0.2 
slack-chat 3.4.2 
```

**Comment by 2hands10fingers** [comment]
I am currently also experiencing this issue.

**Comment by phillipbroberts** [comment]
I am experiencing this as well

**Comment by SLionB** [comment]
Me too

**Comment by echoface** [comment]
me too

**Comment by mazizulak** [comment]
me too

**Comment by orsinium** [comment]
me too

**Comment by zanhk** [comment]
me too

**Comment by merciero** [comment]
same

**Comment by merciero** [comment]
Was someone able to fix this? It looks similar to:
https://github.com/gsingers/slack-jira-plugin/issues/37
https://github.com/gsingers/slack-webex-plugin/issues/2
