### ISSUE TITLE
Uncaught RangeError: out of range index

### ISSUE THREAD

**Issue by rsheldiii** [callahanrts/slack-chat#47]
I got this doing nothing, just opening the chat and letting it be

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package 3.4.2

### Stack Trace

Uncaught RangeError: out of range index

```
At /Users/rsheldon/.atom/packages/slack-chat/node_modules/ws/lib/Receiver.js:382

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/packages/slack-chat/node_modules/ws/lib/Receiver.js:382:24)
    at Receiver.add (/packages/slack-chat/node_modules/ws/lib/Receiver.js:82:3)
    at TLSSocket.firstHandler (/packages/slack-chat/node_modules/ws/lib/WebSocket.js:774:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:543:20)
```

### Commands

```
     -7:51.2.0 command-palette:toggle (atom-pane.pane.active)
     -7:49.9.0 core:move-down (input.hidden-input)
     -7:49.7.0 core:confirm (input.hidden-input)
     -7:49.7.0 rebel-chat:hide (atom-pane.pane.active)
     -7:46.6.0 command-palette:toggle (atom-pane.pane.active)
     -7:45.4.0 core:confirm (input.hidden-input)
     -7:45.4.0 pane:merge-all-panes (atom-pane.pane.active)
     -3:10.5.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:05.9.0 core:move-down (input.hidden-input)
     -3:05.7.0 core:confirm (input.hidden-input)
     -3:05.7.0 settings-view:view-installed-packages (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:02.8.0 core:select-all (input.hidden-input)
     -3:01.6.0 core:confirm (input.hidden-input)
     -2:52.1.0 command-palette:toggle (input#slack-chat.notifications.input-checkbox)
     -2:51.1.0 core:confirm (input.hidden-input)
     -2:51.1.0 slack-chat:toggle (input#slack-chat.notifications.input-checkbox)
```

### Non-Core Packages

```
atomify 0.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.8 
busy-signal 1.3.0 
change-case 0.6.3 
editing-diff 0.2.1 
file-icons 2.1.1 
git-time-machine 1.5.6 
goto-definition 1.2.1 
intentions 1.1.2 
language-babel 2.57.0 
language-haml 0.24.1 
language-javascript-jsx 0.3.7 
linter 2.1.0 
linter-coffeelint 1.2.1 
linter-eslint 8.1.4 
linter-ui-default 1.2.1 
markdown-preview-plus 2.4.9 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-linter 1.6.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
pain-split 1.4.0 
pigments 0.39.1 
project-manager 3.3.4 
react 0.16.2 
react-es6-snippets 0.3.0 
RebelChat 0.8.1 
set-syntax 0.3.2 
slack-chat 3.4.2 
sort-lines 0.14.0 
split-diff 1.2.1 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by aratakokubun** [comment]
I got the same error.
Is there any way to resolve this issue?

**Comment by aratakokubun** [comment]
I resolved the issue.
In my case, I made a mistake to input verification token to the slack token in the slack-chat atom setting.
I cleared the slack token and restarted atom. 
Then, authentication page was opened and I got the token for slack-chat.
After I input the token and restarted atom, I got to be able to use the slack-chat.
