### ISSUE TITLE
Failed to load the slack-chat package

### ISSUE THREAD

**Issue by Shinrai** [callahanrts/slack-chat#49]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package 3.4.2

### Stack Trace

Failed to load the slack-chat package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:19)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:1)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/slack-chat/lib/state-controller.coffee:2:17)
    at /packages/slack-chat/lib/state-controller.coffee:2:1)
    at /packages/slack-chat/lib/state-controller.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:66:33)
    at /packages/slack-chat/lib/slack-chat.coffee:2:19)
    at /packages/slack-chat/lib/slack-chat.coffee:2:1)
    at /packages/slack-chat/lib/slack-chat.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.3/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.23.3/resources/app/src/compile-cache.js:239:29)
```

### Commands

```
```

### Non-Core Packages

```
slack-chat 3.4.2 
teletype 0.6.0 
```

**Comment by KeithETruesdell** [comment]
I got the same thing
