### ISSUE TITLE
Failed to activate the slack-chat package

### ISSUE THREAD

**Issue by SerenadeX** [callahanrts/slack-chat#5]
1. Install slack-chat
2. Hit cmd+m

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v1.0.0
### Stack Trace

Failed to activate the slack-chat package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/Users/rhett/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:414:5)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/node_modules/body-parser/index.js:29:46)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-api.coffee:4:14)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-api.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-chat-view.coffee:6:12)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-chat-view.coffee:2:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-chat.coffee:1:17)
  at Object.<anonymous> (/Users/rhett/.atom/packages/slack-chat/lib/slack-chat.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -0:00.7 slack-chat:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/rhett/Developer",
    "disabledPackages": [
      "atom-gist",
      "symbols-view",
      "linter-javac",
      "linter-scss-lint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
git-log, v0.3.0
git-tab-status, v1.5.3
language-apache, v1.2.0
language-gradle, v0.0.3
language-jade, v0.3.0
linter, v0.12.0
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-tidy, v1.0.0
minimap, v4.6.0
react, v0.9.11
slack-chat, v1.0.0
symbols-tree-view, v0.6.1
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by asarenski** [comment]
@SerenadeX This issue has been solved, but still getting the package up to date.
