### ISSUE TITLE
Failed to load the slack-chat package

### ISSUE THREAD

**Issue by Dashon-Hawkins** [callahanrts/slack-chat#50]
[Enter steps to reproduce:]

1. Open Atom editor
2. As soon as Atom editor opens the following error comes up immediately...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package 3.4.2

### Stack Trace

Failed to load the slack-chat package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/api-workbench/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at /packages/api-workbench/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at /packages/api-workbench/node_modules/atom-space-pen-views/lib/main.js:24:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:19)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:1)
    at /packages/slack-chat/lib/views/slack-chat-view.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/slack-chat/lib/state-controller.coffee:2:17)
    at /packages/slack-chat/lib/state-controller.coffee:2:1)
    at /packages/slack-chat/lib/state-controller.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
```

### Commands

```
```

### Non-Core Packages

```
aligner-css 1.2.1 
aligner-javascript 1.3.0 
altgr 0.1.0 
api-docs 0.0.6 
api-workbench 0.8.48 
atom-agressive-js-iterable 0.1.1 
atom-autocomplete-php 0.25.6 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.32.5 
atom-cform 0.6.0 
atom-cform-yaml 0.5.1-0 
atom-cli-diff 1.9.0 
atom-clock 0.1.16 
atom-css-clean 2.24.1 
atom-css-comb 3.3.1 
atom-css-unit-converter 1.1.1 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-idea 1.2.2 
atom-javascript-console-snippets 0.10.0 
atom-linter-node-dependencies 1.5.0 
atom-meteor-file-snippets 2.0.1 
atom-meteor-snippets 0.1.0 
atom-mysql-snippets 0.3.1 
atom-nodejs-snippets 2.1.1 
atom-psql 0.28.0 
atom-react 0.4.0 
atom-react-alt-templates 0.6.0 
atom-react-instyle 0.2.8 
atom-react-intl-snippets 1.0.2 
atom-react-native-style 0.2.0 
atom-react-proptypes-autocomplete 0.2.2 
atom-react-snippets 0.2.2 
atom-slack-snippets 0.2.0 
atom-sql-list 0.3.1 
atom-ternjs 0.18.3 
atom-tracker 0.3.3 
atom-video 0.1.1 
atom-wordpress 0.3.0 
autocomplete-bash-builtins 0.3.5 
autocomplete-javascript 0.0.2 
autocomplete-meteor-packages 1.3.0 
autocomplete-modules 2.1.0 
autocomplete-solidity 0.3.4 
autocomplete-wordpress-hooks 0.2.3 
autumn-highlighter-syntax 1.13.0 
bdd-react-snippets 0.6.0 
beautify 0.31.0 
bem-levels 1.0.1 
bem-tools 0.1.15 
bemhtml 0.11.0 
bemjson-snippets 0.1.0 
bottom-dock 0.4.4 
build-dockerfile 1.0.1 
build-npm-apm 0.12.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
codelf 12.2.0 
composer 0.5.0 
composer-atom-plugin 0.7.1 
css-color-name 0.4.0 
css-declaration-sorter 1.2.2 
css-from-html 0.1.5 
css-in-js 1.4.0 
css-skeleton-maker 0.1.4 
css-snippets 1.1.0 
css-specificity 0.2.2 
css-spy 0.6.0 
data-ace 0.24.13 
data-atom 0.29.0 
difile 0.3.4 
docblockr 0.13.7 
docker 0.8.0 
dockerletion 0.2.0 
documentation-renderer 0.2.1 
dsc-react-tools 0.6.0 
duplicate-line-or-selection 0.9.0 
es6-javascript 1.0.0 
es6-react-redux-snippets 3.9.0 
etheratom 4.3.7 
eval-javascript 1.2.0 
expand-region 0.4.2 
express-snippets 0.2.0 
expressjs 2.2.0 
fancy-react 0.6.3 
file-icons 2.1.22 
format-javascript-comment 0.2.5 
format-shell 2.0.0 
generate-react-component 0.2.0 
git-auto-stash 0.2.4 
git-control 0.9.0 
git-plus 8.0.0 
git-projects 1.17.0 
git-rebase 0.1.1 
git-time-machine 2.1.0 
gitlab 0.1.3-7 
gitlab-integration 0.4.7 
hey-pane 1.1.0 
highlight-line 0.12.0 
highlight-selected 0.14.0 
html-shorcuts-react 3.0.3 
http-post 1.0.1 
Hydrogen 2.5.1 
hyperclick 0.0.0 
iam-syntax 0.1.5 
ide-bash 1.0.11 
ide-css 0.3.0 
ide-docker 0.0.2 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 1.0.0 
ide-standardjs 0.0.1 
ide-vue 0.1.9 
imdone-atom 2.4.31 
imdone-atom-github 0.1.11 
impress 0.1.1 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
javascript-object-snippets 0.3.0 
javascript-refactor 0.7.1 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
js-hyperclick 1.13.0 
js-refactor 0.8.1 
language-babel 2.85.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-documentation 2.0.1 
language-dots 0.0.4 
language-ethereum 0.3.9 
language-homebrew-formula 1.0.4 
language-ignore 1.7.4 
language-javascript-jsx 0.3.7 
language-javascript-jxa 0.2.8 
language-javascript-plus 1.9.3 
language-mongodb 0.3.1 
language-patch 1.2.0 
language-pgsql 0.2.3 
language-solidity 0.1.0 
language-sql-mysql 0.3.1 
language-wp 0.1.1 
linter 2.2.0 
linter-docker 0.3.2 
linter-eslint 8.4.1 
linter-js-cloudformation-yaml 2.2.1 
linter-sass-lint 1.8.3 
linter-solidity 0.5.0 
linter-ui-default 1.7.1 
local-history 4.3.1 
local-server-express 0.3.1 
lodash-snippets 2.0.0 
MagicPython 1.0.12 
mantrajs 0.5.0 
markdown-preview-plus 3.3.3 
markdown-writer 2.7.5 
materialize-css 0.5.1 
merge-conflicts 1.4.5 
meteor-api 2.20.0 
meteor-assist 0.3.0 
meteor-assist-sanuker 3.1.3 
meteor-helper 0.29.0 
meteor-open-all 0.4.0 
meteor-snippets 0.5.0 
meteor-spacebars 1.0.0 
meteorjs-snippets-es6 1.3.0 
minimap-git-diff 4.3.1 
modern-javascript-snippets 1.1.0 
my-express-nodejs 0.0.10 
new-file-plus 0.2.1 
node-debugger 1.10.1 
node-on-fire 0.1.0 
node-requirer 0.1.12 
npm-install 4.0.4 
npm-outdated 0.6.0 
npm-plus 0.4.0 
nucleon 1.0.4 
nuclide 0.327.0 
nuclide-esformatter 0.3.1 
nuclide-format-js 0.0.46 
nuclide-test-runner-cmd 0.1.0 
open-file-in 1.2.3 
pg-dev 0.8.2 
pg-formatter 0.0.1 
php-composer-completion 0.3.4 
php-integrator-refactoring 1.4.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
platomformio 0.7.1 
postcss-sorting 2.10.0 
project-plus 1.0.0 
puddletown-javascript-node-snippets 1.2.1 
Quick-JavaScript 2.2.0 
quick-query 0.13.0 
random 1.4.1 
re-re-re-react 3.0.0 
react 0.18.0 
react-builder 0.0.1 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-function-to-class 0.2.4 
react-generatr 1.1.1 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-redux-component-snippets 0.0.3 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-redux-snippets 0.1.6 
react-snippets 1.1.1 
react-snippets-for-atom 0.2.0 
react-storybook-snippets 0.3.0 
redux-snippets 0.2.2 
refactor 0.11.5 
repository-file-actions 0.7.0 
rest-client 1.3.1 
s3uploader 1.1.0 
script 3.18.1 
serverless-dashboard 0.2.3 
slack-chat 3.4.2 
smart-daemon-control 0.8.7 
split-diff 1.5.2 
standard-formatter 2.8.0 
styled-components-snippets 0.6.1 
styri-syntax 0.2.0 
symfony-commands 0.4.3 
talking-mango 0.2.1 
teletype 0.13.3 
todo-manager 0.2.10 
todo-show 2.3.0 
tool-bar 1.1.7 
tree-view-git-branch 0.1.2 
treedbox-atom-javascript 2.10.0 
turbo-javascript 1.4.0 
wakanda-syntax 0.1.1 
woocommerce 1.0.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.5.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
wp-dev 0.3.5 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
zip-folder 3.2.0 
```

### Hypothesis: I believe that it is because node module "atom-space-pen-views" is not a global or local NPM package dependency within atom "packages" folder. You must find that package and add it (if it isn't already deprecated). If that doesn't work just uninstall this package because it looks as though no one is maintaining it anymore.

**Comment by Dashon-Hawkins** [comment]
This is the same as #49 , but just a different OS.

**Comment by christyparks420** [comment]
got this error on my first install of atom. soon as i installed it all i got was a lot of red text and told this issue was already reported and took me to this link. only thing is im on windows 10.

**Comment by Exter-dg** [comment]
Same issue for Ubuntu 19.04
