### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by Gerhardk** [callahanrts/slack-chat#6]
Steps to Reproduce:
1. Install slack-chat
2. Wait a bit
3. Error!

**Atom Version**: 0.192.0
**System**: Mac OS X 10.9.5
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v1.0.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/gerhardk19/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/Users/gerhardk19/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421:5)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/node_modules/body-parser/index.js:29:46)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-api.coffee:4:14)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-api.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-chat-view.coffee:6:12)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-chat-view.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-chat.coffee:1:17)
  at Object.<anonymous> (/Users/gerhardk19/.atom/packages/slack-chat/lib/slack-chat.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:667:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:239:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:155:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:193:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:219:24
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:275:26
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "language-jade"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.1.0
autocomplete-plus, v2.10.0
chester-atom-syntax, v0.1.1
minimap, v4.7.6
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by asarenski** [comment]
@Gerhardk This issue has been solved, unfortunately now I'm still working on the plugin to get it up to date.
