### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by angelbotto** [callahanrts/slack-chat#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v1.0.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/angelbotto/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/Users/angelbotto/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421:5)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/node_modules/body-parser/index.js:29:46)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-api.coffee:4:14)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-api.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-chat-view.coffee:6:12)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-chat-view.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-chat.coffee:1:17)
  at Object.<anonymous> (/Users/angelbotto/.atom/packages/slack-chat/lib/slack-chat.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:667:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:239:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:155:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:193:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-detail-view.js:219:24
  at /Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:368:19)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:275:26
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -8:42.7 core:confirm (atom-text-editor.editor.mini)
     -4:49.3 editor:newline (atom-text-editor.editor)
 11x -4:44.9 core:backspace (atom-text-editor.editor)
     -4:33.0 core:cut (atom-text-editor.editor)
     -4:32.1 core:move-left (atom-text-editor.editor)
     -4:31.5 core:save (atom-text-editor.editor)
     -4:30.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:20.9 yard:create (atom-text-editor.editor)
     -2:16.0 core:undo (atom-text-editor.editor)
     -2:13.5 core:move-right (atom-text-editor.editor)
     -2:13.3 core:move-down (atom-text-editor.editor)
     -2:13.1 core:move-left (atom-text-editor.editor)
     -2:12.3 yard:create (atom-text-editor.editor)
     -2:10.0 core:undo (atom-text-editor.editor)
     -1:19.9 core:select-all (atom-text-editor.editor.mini)
     -1:19.2 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
aligner-css, v1.2.0
aligner-ruby, v1.2.1
aligner-scss, v1.0.1
autocomplete-ruby, v0.1.0
color-picker, v1.7.0
jshint, v1.3.3
linter, v0.12.1
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
react, v0.11.5
react-snippets, v0.1.4
travis-ci-status, v0.13.0
yard, v0.3.1

# Dev
No dev packages
```

**Comment by asarenski** [comment]
@angelbotto This has been corrected. Unfortunately I'm still working on the package to get it up-to-date.
