### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

### ISSUE THREAD

**Issue by jchannon** [callahanrts/slack-chat#9]
1. Installing the plugin resulted in this error
   <br/><br/><br/>
   ![screen shot 2015-05-09 at 19 17 20](https://cloud.githubusercontent.com/assets/105126/7551439/0993781a-f680-11e4-95ad-59f5ca238da3.png)

**Atom Version**: 0.198.0
**System**: Mac OS X 10.9.5
**Thrown From**: [slack-chat](https://github.com/callahanrts/slack-chat) package, v1.0.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/jonathan/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function.wrapfunction (/Users/jonathan/.atom/packages/slack-chat/node_modules/body-parser/node_modules/depd/index.js:421:5)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/node_modules/body-parser/index.js:29:46)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-api.coffee:4:14)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-api.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-chat-view.coffee:6:12)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-chat-view.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-chat.coffee:1:17)
  at Object.<anonymous> (/Users/jonathan/.atom/packages/slack-chat/lib/slack-chat.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:711:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:259:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:414:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:323:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -2:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v1.1.5
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
highlight-selected, v0.9.2
isotope-ui, v2.2.0
linter, v0.12.1
monokai, v0.14.0
omnisharp-atom, v0.4.16

# Dev
No dev packages
```

**Comment by asarenski** [comment]
@jchannon Thanks for the update. I merged a PR to mitigate this issue. I'll need to follow-up and make sure it makes its way to the apm.

**Comment by jchannon** [comment]
Thanks! Sorry just realised this is a duplicate issue but man if this plugin works it will be amazing!! :smile: :+1:

**Comment by jchannon** [comment]
Please let me know once its on apm though :smiley:
